### ISSUE TITLE
Grammatical english errors

### ISSUE THREAD

**Issue by AlexandreBobis** [algosup/2022-2023-project-5-algorithmics-Team-2#1]
[README.md](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-2/files/11461475/README.md)

objectif --> objective
Champagne1 --> Champagne
Specification --> Specifications

**Comment by AlexandreBobis** [comment]
Add label

**Comment by JanaganSaravanan** [comment]
Hi, i have updated the file. please check it out.
